services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-tracker-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 